[package]
authors = ["Weichwerke Heidrich Software"]
categories = ["no-std"]
description = "A tiny crate to access a strongly typed common weakness enumeration (cwe) object."
edition = "2024"
keywords = ["cwe", "security"]
license = "MIT"
name = "cwenum"
readme = "README.md"
repository = "https://github.com/Weichwerke-Heidrich-Software/cwenum"
version = "1.0.1"

[lib]
name = "cwenum"
crate-type = ["rlib"]

[dependencies]
serde_crate = { package = "serde", version = "1.0", features = ["derive"], optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
iterable = []
serde = ["serde_crate", "str"]
std = []
str = []
