import os
import requests
import shutil
import xml.etree.ElementTree as ET
import zipfile

URL = 'https://cwe.mitre.org/data/xml/cwec_latest.xml.zip'
DIR = "dev_data"
CWEC_ZIP = os.path.join(DIR, "cwec.zip")
CWEC_XML = os.path.join(DIR, "cwec.xml")
RUSTFILE = os.path.join("src", "cwe.rs")

FILE_TEMPLATE = """
// This code is generated by generate_code.py, do not modify it manually.

pub enum CWE {{
    {variants}
}}
"""


def download_cwec_zip(url):
    response = requests.get(url)
    with open(CWEC_ZIP, 'wb') as file:
        file.write(response.content)

def extract_cwec_xml():
    with zipfile.ZipFile(CWEC_ZIP, 'r') as zip_ref:
        temp_dir = os.path.join(DIR, "temp")
        zip_ref.extractall(temp_dir)
        extracted_file = os.path.join(temp_dir, zip_ref.namelist()[0])
        shutil.move(extracted_file, CWEC_XML)
        shutil.rmtree(temp_dir)

def assure_file():
    if not os.path.exists(DIR):
        os.makedirs(DIR)
    if not os.path.exists(CWEC_ZIP):    
        download_cwec_zip(URL)
    if not os.path.exists(CWEC_XML):
        extract_cwec_xml()

def parse_cwec_xml():
    tree = ET.parse(CWEC_XML)
    root = tree.getroot()
    cwec = []
    namespace = {'cwe': 'http://cwe.mitre.org/cwe-7'}
    
    for weakness in root.findall('.//cwe:Weakness', namespace):
        cwe_id = weakness.get('ID')
        cwe_name = weakness.get('Name')
        cwec.append({'ID': cwe_id, 'Name': cwe_name})
    
    cwec.sort(key=lambda x: int(x['ID']))

    return cwec

def write_to_file(cwec):
    variants = []
    for cwe in cwec:
        variants.append(f"CWE_{cwe['ID']}")

    with open(RUSTFILE, 'w') as file:
        file.write(FILE_TEMPLATE.format(variants=",\n".join(variants)))

def main():
    assure_file()
    cwec = parse_cwec_xml()
    write_to_file(cwec)

if __name__ == "__main__":
    main()
