import os
import requests
import shutil
import xml.etree.ElementTree as ET
import zipfile

URL = 'https://cwe.mitre.org/data/xml/cwec_latest.xml.zip'
DIR = "dev_data"
CWEC_ZIP = os.path.join(DIR, "cwec.zip")
CWEC_XML = os.path.join(DIR, "cwec.xml")
RUSTFILE = os.path.join("src", "cwe.rs")

FILE_TEMPLATE = """
// This code is generated by generate_code.py, do not modify it manually.

/// The Common Weakness Enumeration (CWE) is a list of software weaknesses maintained by MITRE.
/// 
/// # Example
///
/// ```
/// use cwenum::Cwe;
///
/// let cwe = Cwe::Cwe89;
/// // The enum is cloneable...
/// let _cwe_clone = cwe.clone();
/// // ...copyable...
/// let _cwe_copy = cwe;
/// // ...comparable...
/// assert_eq!(cwe, Cwe::Cwe89);
/// // ...and hashable.
/// let mut map = std::collections::HashMap::new();
/// map.insert(cwe, "CWE-89");
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Cwe {{
    {variants}
}}
"""

VARIANT_TEMPLATE = """
    /// ### {name}
    ///
    /// {description}
    Cwe{id},
"""

def download_cwec_zip(url):
    response = requests.get(url)
    with open(CWEC_ZIP, 'wb') as file:
        file.write(response.content)

def extract_cwec_xml():
    with zipfile.ZipFile(CWEC_ZIP, 'r') as zip_ref:
        temp_dir = os.path.join(DIR, "temp")
        zip_ref.extractall(temp_dir)
        extracted_file = os.path.join(temp_dir, zip_ref.namelist()[0])
        shutil.move(extracted_file, CWEC_XML)
        shutil.rmtree(temp_dir)

def assure_file():
    if not os.path.exists(DIR):
        os.makedirs(DIR)
    if not os.path.exists(CWEC_ZIP):    
        download_cwec_zip(URL)
    if not os.path.exists(CWEC_XML):
        extract_cwec_xml()

def parse_cwec_xml():
    tree = ET.parse(CWEC_XML)
    root = tree.getroot()
    cwec = []
    namespace = {'cwe': 'http://cwe.mitre.org/cwe-7'}
    
    for weakness in root.findall('.//cwe:Weakness', namespace):
        cwe_id = weakness.get('ID')
        cwe_name = weakness.get('Name')
        cwe_description = weakness.find('cwe:Description', namespace).text
        cwe_description = cwe_description.replace('\n', ' ').replace('\r', ' ').replace('\t', ' ')
        while '  ' in cwe_description:
            cwe_description = cwe_description.replace('  ', ' ')
        cwec.append({'ID': cwe_id,
                     'Name': cwe_name,
                     'Description': cwe_description})
    
    cwec.sort(key=lambda x: int(x['ID']))

    return cwec

def write_to_file(cwec):
    variants = []
    for cwe in cwec:
        variants.append(VARIANT_TEMPLATE.format(id=cwe['ID'],
                                                name=cwe['Name'],
                                                description=cwe['Description']))

    with open(RUSTFILE, 'w') as file:
        file.write(FILE_TEMPLATE.format(variants="\n".join(variants)))

def main():
    assure_file()
    cwec = parse_cwec_xml()
    write_to_file(cwec)

if __name__ == "__main__":
    main()
