// This code is generated by generate_code.py, do not modify it manually.

pub enum CWE {
    /// J2EE Misconfiguration: Data Transmission Without Encryption
    Cwe5,

    /// J2EE Misconfiguration: Insufficient Session-ID Length
    Cwe6,

    /// J2EE Misconfiguration: Missing Custom Error Page
    Cwe7,

    /// J2EE Misconfiguration: Entity Bean Declared Remote
    Cwe8,

    /// J2EE Misconfiguration: Weak Access Permissions for EJB Methods
    Cwe9,

    /// ASP.NET Misconfiguration: Creating Debug Binary
    Cwe11,

    /// ASP.NET Misconfiguration: Missing Custom Error Page
    Cwe12,

    /// ASP.NET Misconfiguration: Password in Configuration File
    Cwe13,

    /// Compiler Removal of Code to Clear Buffers
    Cwe14,

    /// External Control of System or Configuration Setting
    Cwe15,

    /// Improper Input Validation
    Cwe20,

    /// Improper Limitation of a Pathname to a Restricted Directory ('Path Traversal')
    Cwe22,

    /// Relative Path Traversal
    Cwe23,

    /// Path Traversal: '../filedir'
    Cwe24,

    /// Path Traversal: '/../filedir'
    Cwe25,

    /// Path Traversal: '/dir/../filename'
    Cwe26,

    /// Path Traversal: 'dir/../../filename'
    Cwe27,

    /// Path Traversal: '..\filedir'
    Cwe28,

    /// Path Traversal: '\..\filename'
    Cwe29,

    /// Path Traversal: '\dir\..\filename'
    Cwe30,

    /// Path Traversal: 'dir\..\..\filename'
    Cwe31,

    /// Path Traversal: '...' (Triple Dot)
    Cwe32,

    /// Path Traversal: '....' (Multiple Dot)
    Cwe33,

    /// Path Traversal: '....//'
    Cwe34,

    /// Path Traversal: '.../...//'
    Cwe35,

    /// Absolute Path Traversal
    Cwe36,

    /// Path Traversal: '/absolute/pathname/here'
    Cwe37,

    /// Path Traversal: '\absolute\pathname\here'
    Cwe38,

    /// Path Traversal: 'C:dirname'
    Cwe39,

    /// Path Traversal: '\\UNC\share\name\' (Windows UNC Share)
    Cwe40,

    /// Improper Resolution of Path Equivalence
    Cwe41,

    /// Path Equivalence: 'filename.' (Trailing Dot)
    Cwe42,

    /// Path Equivalence: 'filename....' (Multiple Trailing Dot)
    Cwe43,

    /// Path Equivalence: 'file.name' (Internal Dot)
    Cwe44,

    /// Path Equivalence: 'file...name' (Multiple Internal Dot)
    Cwe45,

    /// Path Equivalence: 'filename ' (Trailing Space)
    Cwe46,

    /// Path Equivalence: ' filename' (Leading Space)
    Cwe47,

    /// Path Equivalence: 'file name' (Internal Whitespace)
    Cwe48,

    /// Path Equivalence: 'filename/' (Trailing Slash)
    Cwe49,

    /// Path Equivalence: '//multiple/leading/slash'
    Cwe50,

    /// Path Equivalence: '/multiple//internal/slash'
    Cwe51,

    /// Path Equivalence: '/multiple/trailing/slash//'
    Cwe52,

    /// Path Equivalence: '\multiple\\internal\backslash'
    Cwe53,

    /// Path Equivalence: 'filedir\' (Trailing Backslash)
    Cwe54,

    /// Path Equivalence: '/./' (Single Dot Directory)
    Cwe55,

    /// Path Equivalence: 'filedir*' (Wildcard)
    Cwe56,

    /// Path Equivalence: 'fakedir/../realdir/filename'
    Cwe57,

    /// Path Equivalence: Windows 8.3 Filename
    Cwe58,

    /// Improper Link Resolution Before File Access ('Link Following')
    Cwe59,

    /// UNIX Symbolic Link (Symlink) Following
    Cwe61,

    /// UNIX Hard Link
    Cwe62,

    /// Windows Shortcut Following (.LNK)
    Cwe64,

    /// Windows Hard Link
    Cwe65,

    /// Improper Handling of File Names that Identify Virtual Resources
    Cwe66,

    /// Improper Handling of Windows Device Names
    Cwe67,

    /// Improper Handling of Windows ::DATA Alternate Data Stream
    Cwe69,

    /// DEPRECATED: Apple '.DS_Store'
    Cwe71,

    /// Improper Handling of Apple HFS+ Alternate Data Stream Path
    Cwe72,

    /// External Control of File Name or Path
    Cwe73,

    /// Improper Neutralization of Special Elements in Output Used by a Downstream Component ('Injection')
    Cwe74,

    /// Failure to Sanitize Special Elements into a Different Plane (Special Element Injection)
    Cwe75,

    /// Improper Neutralization of Equivalent Special Elements
    Cwe76,

    /// Improper Neutralization of Special Elements used in a Command ('Command Injection')
    Cwe77,

    /// Improper Neutralization of Special Elements used in an OS Command ('OS Command Injection')
    Cwe78,

    /// Improper Neutralization of Input During Web Page Generation ('Cross-site Scripting')
    Cwe79,

    /// Improper Neutralization of Script-Related HTML Tags in a Web Page (Basic XSS)
    Cwe80,

    /// Improper Neutralization of Script in an Error Message Web Page
    Cwe81,

    /// Improper Neutralization of Script in Attributes of IMG Tags in a Web Page
    Cwe82,

    /// Improper Neutralization of Script in Attributes in a Web Page
    Cwe83,

    /// Improper Neutralization of Encoded URI Schemes in a Web Page
    Cwe84,

    /// Doubled Character XSS Manipulations
    Cwe85,

    /// Improper Neutralization of Invalid Characters in Identifiers in Web Pages
    Cwe86,

    /// Improper Neutralization of Alternate XSS Syntax
    Cwe87,

    /// Improper Neutralization of Argument Delimiters in a Command ('Argument Injection')
    Cwe88,

    /// Improper Neutralization of Special Elements used in an SQL Command ('SQL Injection')
    Cwe89,

    /// Improper Neutralization of Special Elements used in an LDAP Query ('LDAP Injection')
    Cwe90,

    /// XML Injection (aka Blind XPath Injection)
    Cwe91,

    /// DEPRECATED: Improper Sanitization of Custom Special Characters
    Cwe92,

    /// Improper Neutralization of CRLF Sequences ('CRLF Injection')
    Cwe93,

    /// Improper Control of Generation of Code ('Code Injection')
    Cwe94,

    /// Improper Neutralization of Directives in Dynamically Evaluated Code ('Eval Injection')
    Cwe95,

    /// Improper Neutralization of Directives in Statically Saved Code ('Static Code Injection')
    Cwe96,

    /// Improper Neutralization of Server-Side Includes (SSI) Within a Web Page
    Cwe97,

    /// Improper Control of Filename for Include/Require Statement in PHP Program ('PHP Remote File Inclusion')
    Cwe98,

    /// Improper Control of Resource Identifiers ('Resource Injection')
    Cwe99,

    /// Struts: Duplicate Validation Forms
    Cwe102,

    /// Struts: Incomplete validate() Method Definition
    Cwe103,

    /// Struts: Form Bean Does Not Extend Validation Class
    Cwe104,

    /// Struts: Form Field Without Validator
    Cwe105,

    /// Struts: Plug-in Framework not in Use
    Cwe106,

    /// Struts: Unused Validation Form
    Cwe107,

    /// Struts: Unvalidated Action Form
    Cwe108,

    /// Struts: Validator Turned Off
    Cwe109,

    /// Struts: Validator Without Form Field
    Cwe110,

    /// Direct Use of Unsafe JNI
    Cwe111,

    /// Missing XML Validation
    Cwe112,

    /// Improper Neutralization of CRLF Sequences in HTTP Headers ('HTTP Request/Response Splitting')
    Cwe113,

    /// Process Control
    Cwe114,

    /// Misinterpretation of Input
    Cwe115,

    /// Improper Encoding or Escaping of Output
    Cwe116,

    /// Improper Output Neutralization for Logs
    Cwe117,

    /// Incorrect Access of Indexable Resource ('Range Error')
    Cwe118,

    /// Improper Restriction of Operations within the Bounds of a Memory Buffer
    Cwe119,

    /// Buffer Copy without Checking Size of Input ('Classic Buffer Overflow')
    Cwe120,

    /// Stack-based Buffer Overflow
    Cwe121,

    /// Heap-based Buffer Overflow
    Cwe122,

    /// Write-what-where Condition
    Cwe123,

    /// Buffer Underwrite ('Buffer Underflow')
    Cwe124,

    /// Out-of-bounds Read
    Cwe125,

    /// Buffer Over-read
    Cwe126,

    /// Buffer Under-read
    Cwe127,

    /// Wrap-around Error
    Cwe128,

    /// Improper Validation of Array Index
    Cwe129,

    /// Improper Handling of Length Parameter Inconsistency
    Cwe130,

    /// Incorrect Calculation of Buffer Size
    Cwe131,

    /// DEPRECATED: Miscalculated Null Termination
    Cwe132,

    /// Use of Externally-Controlled Format String
    Cwe134,

    /// Incorrect Calculation of Multi-Byte String Length
    Cwe135,

    /// Improper Neutralization of Special Elements
    Cwe138,

    /// Improper Neutralization of Delimiters
    Cwe140,

    /// Improper Neutralization of Parameter/Argument Delimiters
    Cwe141,

    /// Improper Neutralization of Value Delimiters
    Cwe142,

    /// Improper Neutralization of Record Delimiters
    Cwe143,

    /// Improper Neutralization of Line Delimiters
    Cwe144,

    /// Improper Neutralization of Section Delimiters
    Cwe145,

    /// Improper Neutralization of Expression/Command Delimiters
    Cwe146,

    /// Improper Neutralization of Input Terminators
    Cwe147,

    /// Improper Neutralization of Input Leaders
    Cwe148,

    /// Improper Neutralization of Quoting Syntax
    Cwe149,

    /// Improper Neutralization of Escape, Meta, or Control Sequences
    Cwe150,

    /// Improper Neutralization of Comment Delimiters
    Cwe151,

    /// Improper Neutralization of Macro Symbols
    Cwe152,

    /// Improper Neutralization of Substitution Characters
    Cwe153,

    /// Improper Neutralization of Variable Name Delimiters
    Cwe154,

    /// Improper Neutralization of Wildcards or Matching Symbols
    Cwe155,

    /// Improper Neutralization of Whitespace
    Cwe156,

    /// Failure to Sanitize Paired Delimiters
    Cwe157,

    /// Improper Neutralization of Null Byte or NUL Character
    Cwe158,

    /// Improper Handling of Invalid Use of Special Elements
    Cwe159,

    /// Improper Neutralization of Leading Special Elements
    Cwe160,

    /// Improper Neutralization of Multiple Leading Special Elements
    Cwe161,

    /// Improper Neutralization of Trailing Special Elements
    Cwe162,

    /// Improper Neutralization of Multiple Trailing Special Elements
    Cwe163,

    /// Improper Neutralization of Internal Special Elements
    Cwe164,

    /// Improper Neutralization of Multiple Internal Special Elements
    Cwe165,

    /// Improper Handling of Missing Special Element
    Cwe166,

    /// Improper Handling of Additional Special Element
    Cwe167,

    /// Improper Handling of Inconsistent Special Elements
    Cwe168,

    /// Improper Null Termination
    Cwe170,

    /// Encoding Error
    Cwe172,

    /// Improper Handling of Alternate Encoding
    Cwe173,

    /// Double Decoding of the Same Data
    Cwe174,

    /// Improper Handling of Mixed Encoding
    Cwe175,

    /// Improper Handling of Unicode Encoding
    Cwe176,

    /// Improper Handling of URL Encoding (Hex Encoding)
    Cwe177,

    /// Improper Handling of Case Sensitivity
    Cwe178,

    /// Incorrect Behavior Order: Early Validation
    Cwe179,

    /// Incorrect Behavior Order: Validate Before Canonicalize
    Cwe180,

    /// Incorrect Behavior Order: Validate Before Filter
    Cwe181,

    /// Collapse of Data into Unsafe Value
    Cwe182,

    /// Permissive List of Allowed Inputs
    Cwe183,

    /// Incomplete List of Disallowed Inputs
    Cwe184,

    /// Incorrect Regular Expression
    Cwe185,

    /// Overly Restrictive Regular Expression
    Cwe186,

    /// Partial String Comparison
    Cwe187,

    /// Reliance on Data/Memory Layout
    Cwe188,

    /// Integer Overflow or Wraparound
    Cwe190,

    /// Integer Underflow (Wrap or Wraparound)
    Cwe191,

    /// Integer Coercion Error
    Cwe192,

    /// Off-by-one Error
    Cwe193,

    /// Unexpected Sign Extension
    Cwe194,

    /// Signed to Unsigned Conversion Error
    Cwe195,

    /// Unsigned to Signed Conversion Error
    Cwe196,

    /// Numeric Truncation Error
    Cwe197,

    /// Use of Incorrect Byte Ordering
    Cwe198,

    /// Exposure of Sensitive Information to an Unauthorized Actor
    Cwe200,

    /// Insertion of Sensitive Information Into Sent Data
    Cwe201,

    /// Exposure of Sensitive Information Through Data Queries
    Cwe202,

    /// Observable Discrepancy
    Cwe203,

    /// Observable Response Discrepancy
    Cwe204,

    /// Observable Behavioral Discrepancy
    Cwe205,

    /// Observable Internal Behavioral Discrepancy
    Cwe206,

    /// Observable Behavioral Discrepancy With Equivalent Products
    Cwe207,

    /// Observable Timing Discrepancy
    Cwe208,

    /// Generation of Error Message Containing Sensitive Information
    Cwe209,

    /// Self-generated Error Message Containing Sensitive Information
    Cwe210,

    /// Externally-Generated Error Message Containing Sensitive Information
    Cwe211,

    /// Improper Removal of Sensitive Information Before Storage or Transfer
    Cwe212,

    /// Exposure of Sensitive Information Due to Incompatible Policies
    Cwe213,

    /// Invocation of Process Using Visible Sensitive Information
    Cwe214,

    /// Insertion of Sensitive Information Into Debugging Code
    Cwe215,

    /// DEPRECATED: Containment Errors (Container Errors)
    Cwe216,

    /// DEPRECATED: Failure to Protect Stored Data from Modification
    Cwe217,

    /// DEPRECATED: Failure to provide confidentiality for stored data
    Cwe218,

    /// Storage of File with Sensitive Data Under Web Root
    Cwe219,

    /// Storage of File With Sensitive Data Under FTP Root
    Cwe220,

    /// Information Loss or Omission
    Cwe221,

    /// Truncation of Security-relevant Information
    Cwe222,

    /// Omission of Security-relevant Information
    Cwe223,

    /// Obscured Security-relevant Information by Alternate Name
    Cwe224,

    /// DEPRECATED: General Information Management Problems
    Cwe225,

    /// Sensitive Information in Resource Not Removed Before Reuse
    Cwe226,

    /// Improper Handling of Syntactically Invalid Structure
    Cwe228,

    /// Improper Handling of Values
    Cwe229,

    /// Improper Handling of Missing Values
    Cwe230,

    /// Improper Handling of Extra Values
    Cwe231,

    /// Improper Handling of Undefined Values
    Cwe232,

    /// Improper Handling of Parameters
    Cwe233,

    /// Failure to Handle Missing Parameter
    Cwe234,

    /// Improper Handling of Extra Parameters
    Cwe235,

    /// Improper Handling of Undefined Parameters
    Cwe236,

    /// Improper Handling of Structural Elements
    Cwe237,

    /// Improper Handling of Incomplete Structural Elements
    Cwe238,

    /// Failure to Handle Incomplete Element
    Cwe239,

    /// Improper Handling of Inconsistent Structural Elements
    Cwe240,

    /// Improper Handling of Unexpected Data Type
    Cwe241,

    /// Use of Inherently Dangerous Function
    Cwe242,

    /// Creation of chroot Jail Without Changing Working Directory
    Cwe243,

    /// Improper Clearing of Heap Memory Before Release ('Heap Inspection')
    Cwe244,

    /// J2EE Bad Practices: Direct Management of Connections
    Cwe245,

    /// J2EE Bad Practices: Direct Use of Sockets
    Cwe246,

    /// DEPRECATED: Reliance on DNS Lookups in a Security Decision
    Cwe247,

    /// Uncaught Exception
    Cwe248,

    /// DEPRECATED: Often Misused: Path Manipulation
    Cwe249,

    /// Execution with Unnecessary Privileges
    Cwe250,

    /// Unchecked Return Value
    Cwe252,

    /// Incorrect Check of Function Return Value
    Cwe253,

    /// Plaintext Storage of a Password
    Cwe256,

    /// Storing Passwords in a Recoverable Format
    Cwe257,

    /// Empty Password in Configuration File
    Cwe258,

    /// Use of Hard-coded Password
    Cwe259,

    /// Password in Configuration File
    Cwe260,

    /// Weak Encoding for Password
    Cwe261,

    /// Not Using Password Aging
    Cwe262,

    /// Password Aging with Long Expiration
    Cwe263,

    /// Incorrect Privilege Assignment
    Cwe266,

    /// Privilege Defined With Unsafe Actions
    Cwe267,

    /// Privilege Chaining
    Cwe268,

    /// Improper Privilege Management
    Cwe269,

    /// Privilege Context Switching Error
    Cwe270,

    /// Privilege Dropping / Lowering Errors
    Cwe271,

    /// Least Privilege Violation
    Cwe272,

    /// Improper Check for Dropped Privileges
    Cwe273,

    /// Improper Handling of Insufficient Privileges
    Cwe274,

    /// Incorrect Default Permissions
    Cwe276,

    /// Insecure Inherited Permissions
    Cwe277,

    /// Insecure Preserved Inherited Permissions
    Cwe278,

    /// Incorrect Execution-Assigned Permissions
    Cwe279,

    /// Improper Handling of Insufficient Permissions or Privileges
    Cwe280,

    /// Improper Preservation of Permissions
    Cwe281,

    /// Improper Ownership Management
    Cwe282,

    /// Unverified Ownership
    Cwe283,

    /// Improper Access Control
    Cwe284,

    /// Improper Authorization
    Cwe285,

    /// Incorrect User Management
    Cwe286,

    /// Improper Authentication
    Cwe287,

    /// Authentication Bypass Using an Alternate Path or Channel
    Cwe288,

    /// Authentication Bypass by Alternate Name
    Cwe289,

    /// Authentication Bypass by Spoofing
    Cwe290,

    /// Reliance on IP Address for Authentication
    Cwe291,

    /// DEPRECATED: Trusting Self-reported DNS Name
    Cwe292,

    /// Using Referer Field for Authentication
    Cwe293,

    /// Authentication Bypass by Capture-replay
    Cwe294,

    /// Improper Certificate Validation
    Cwe295,

    /// Improper Following of a Certificate's Chain of Trust
    Cwe296,

    /// Improper Validation of Certificate with Host Mismatch
    Cwe297,

    /// Improper Validation of Certificate Expiration
    Cwe298,

    /// Improper Check for Certificate Revocation
    Cwe299,

    /// Channel Accessible by Non-Endpoint
    Cwe300,

    /// Reflection Attack in an Authentication Protocol
    Cwe301,

    /// Authentication Bypass by Assumed-Immutable Data
    Cwe302,

    /// Incorrect Implementation of Authentication Algorithm
    Cwe303,

    /// Missing Critical Step in Authentication
    Cwe304,

    /// Authentication Bypass by Primary Weakness
    Cwe305,

    /// Missing Authentication for Critical Function
    Cwe306,

    /// Improper Restriction of Excessive Authentication Attempts
    Cwe307,

    /// Use of Single-factor Authentication
    Cwe308,

    /// Use of Password System for Primary Authentication
    Cwe309,

    /// Missing Encryption of Sensitive Data
    Cwe311,

    /// Cleartext Storage of Sensitive Information
    Cwe312,

    /// Cleartext Storage in a File or on Disk
    Cwe313,

    /// Cleartext Storage in the Registry
    Cwe314,

    /// Cleartext Storage of Sensitive Information in a Cookie
    Cwe315,

    /// Cleartext Storage of Sensitive Information in Memory
    Cwe316,

    /// Cleartext Storage of Sensitive Information in GUI
    Cwe317,

    /// Cleartext Storage of Sensitive Information in Executable
    Cwe318,

    /// Cleartext Transmission of Sensitive Information
    Cwe319,

    /// Use of Hard-coded Cryptographic Key
    Cwe321,

    /// Key Exchange without Entity Authentication
    Cwe322,

    /// Reusing a Nonce, Key Pair in Encryption
    Cwe323,

    /// Use of a Key Past its Expiration Date
    Cwe324,

    /// Missing Cryptographic Step
    Cwe325,

    /// Inadequate Encryption Strength
    Cwe326,

    /// Use of a Broken or Risky Cryptographic Algorithm
    Cwe327,

    /// Use of Weak Hash
    Cwe328,

    /// Generation of Predictable IV with CBC Mode
    Cwe329,

    /// Use of Insufficiently Random Values
    Cwe330,

    /// Insufficient Entropy
    Cwe331,

    /// Insufficient Entropy in PRNG
    Cwe332,

    /// Improper Handling of Insufficient Entropy in TRNG
    Cwe333,

    /// Small Space of Random Values
    Cwe334,

    /// Incorrect Usage of Seeds in Pseudo-Random Number Generator (PRNG)
    Cwe335,

    /// Same Seed in Pseudo-Random Number Generator (PRNG)
    Cwe336,

    /// Predictable Seed in Pseudo-Random Number Generator (PRNG)
    Cwe337,

    /// Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)
    Cwe338,

    /// Small Seed Space in PRNG
    Cwe339,

    /// Generation of Predictable Numbers or Identifiers
    Cwe340,

    /// Predictable from Observable State
    Cwe341,

    /// Predictable Exact Value from Previous Values
    Cwe342,

    /// Predictable Value Range from Previous Values
    Cwe343,

    /// Use of Invariant Value in Dynamically Changing Context
    Cwe344,

    /// Insufficient Verification of Data Authenticity
    Cwe345,

    /// Origin Validation Error
    Cwe346,

    /// Improper Verification of Cryptographic Signature
    Cwe347,

    /// Use of Less Trusted Source
    Cwe348,

    /// Acceptance of Extraneous Untrusted Data With Trusted Data
    Cwe349,

    /// Reliance on Reverse DNS Resolution for a Security-Critical Action
    Cwe350,

    /// Insufficient Type Distinction
    Cwe351,

    /// Cross-Site Request Forgery (CSRF)
    Cwe352,

    /// Missing Support for Integrity Check
    Cwe353,

    /// Improper Validation of Integrity Check Value
    Cwe354,

    /// Product UI does not Warn User of Unsafe Actions
    Cwe356,

    /// Insufficient UI Warning of Dangerous Operations
    Cwe357,

    /// Improperly Implemented Security Check for Standard
    Cwe358,

    /// Exposure of Private Personal Information to an Unauthorized Actor
    Cwe359,

    /// Trust of System Event Data
    Cwe360,

    /// Concurrent Execution using Shared Resource with Improper Synchronization ('Race Condition')
    Cwe362,

    /// Race Condition Enabling Link Following
    Cwe363,

    /// Signal Handler Race Condition
    Cwe364,

    /// DEPRECATED: Race Condition in Switch
    Cwe365,

    /// Race Condition within a Thread
    Cwe366,

    /// Time-of-check Time-of-use (TOCTOU) Race Condition
    Cwe367,

    /// Context Switching Race Condition
    Cwe368,

    /// Divide By Zero
    Cwe369,

    /// Missing Check for Certificate Revocation after Initial Check
    Cwe370,

    /// Incomplete Internal State Distinction
    Cwe372,

    /// DEPRECATED: State Synchronization Error
    Cwe373,

    /// Passing Mutable Objects to an Untrusted Method
    Cwe374,

    /// Returning a Mutable Object to an Untrusted Caller
    Cwe375,

    /// Insecure Temporary File
    Cwe377,

    /// Creation of Temporary File With Insecure Permissions
    Cwe378,

    /// Creation of Temporary File in Directory with Insecure Permissions
    Cwe379,

    /// J2EE Bad Practices: Use of System.exit()
    Cwe382,

    /// J2EE Bad Practices: Direct Use of Threads
    Cwe383,

    /// Session Fixation
    Cwe384,

    /// Covert Timing Channel
    Cwe385,

    /// Symbolic Name not Mapping to Correct Object
    Cwe386,

    /// Detection of Error Condition Without Action
    Cwe390,

    /// Unchecked Error Condition
    Cwe391,

    /// Missing Report of Error Condition
    Cwe392,

    /// Return of Wrong Status Code
    Cwe393,

    /// Unexpected Status Code or Return Value
    Cwe394,

    /// Use of NullPointerException Catch to Detect NULL Pointer Dereference
    Cwe395,

    /// Declaration of Catch for Generic Exception
    Cwe396,

    /// Declaration of Throws for Generic Exception
    Cwe397,

    /// Uncontrolled Resource Consumption
    Cwe400,

    /// Missing Release of Memory after Effective Lifetime
    Cwe401,

    /// Transmission of Private Resources into a New Sphere ('Resource Leak')
    Cwe402,

    /// Exposure of File Descriptor to Unintended Control Sphere ('File Descriptor Leak')
    Cwe403,

    /// Improper Resource Shutdown or Release
    Cwe404,

    /// Asymmetric Resource Consumption (Amplification)
    Cwe405,

    /// Insufficient Control of Network Message Volume (Network Amplification)
    Cwe406,

    /// Inefficient Algorithmic Complexity
    Cwe407,

    /// Incorrect Behavior Order: Early Amplification
    Cwe408,

    /// Improper Handling of Highly Compressed Data (Data Amplification)
    Cwe409,

    /// Insufficient Resource Pool
    Cwe410,

    /// Unrestricted Externally Accessible Lock
    Cwe412,

    /// Improper Resource Locking
    Cwe413,

    /// Missing Lock Check
    Cwe414,

    /// Double Free
    Cwe415,

    /// Use After Free
    Cwe416,

    /// Unprotected Primary Channel
    Cwe419,

    /// Unprotected Alternate Channel
    Cwe420,

    /// Race Condition During Access to Alternate Channel
    Cwe421,

    /// Unprotected Windows Messaging Channel ('Shatter')
    Cwe422,

    /// DEPRECATED: Proxied Trusted Channel
    Cwe423,

    /// Improper Protection of Alternate Path
    Cwe424,

    /// Direct Request ('Forced Browsing')
    Cwe425,

    /// Untrusted Search Path
    Cwe426,

    /// Uncontrolled Search Path Element
    Cwe427,

    /// Unquoted Search Path or Element
    Cwe428,

    /// Deployment of Wrong Handler
    Cwe430,

    /// Missing Handler
    Cwe431,

    /// Dangerous Signal Handler not Disabled During Sensitive Operations
    Cwe432,

    /// Unparsed Raw Web Content Delivery
    Cwe433,

    /// Unrestricted Upload of File with Dangerous Type
    Cwe434,

    /// Improper Interaction Between Multiple Correctly-Behaving Entities
    Cwe435,

    /// Interpretation Conflict
    Cwe436,

    /// Incomplete Model of Endpoint Features
    Cwe437,

    /// Behavioral Change in New Version or Environment
    Cwe439,

    /// Expected Behavior Violation
    Cwe440,

    /// Unintended Proxy or Intermediary ('Confused Deputy')
    Cwe441,

    /// DEPRECATED: HTTP response splitting
    Cwe443,

    /// Inconsistent Interpretation of HTTP Requests ('HTTP Request/Response Smuggling')
    Cwe444,

    /// UI Discrepancy for Security Feature
    Cwe446,

    /// Unimplemented or Unsupported Feature in UI
    Cwe447,

    /// Obsolete Feature in UI
    Cwe448,

    /// The UI Performs the Wrong Action
    Cwe449,

    /// Multiple Interpretations of UI Input
    Cwe450,

    /// User Interface (UI) Misrepresentation of Critical Information
    Cwe451,

    /// Insecure Default Variable Initialization
    Cwe453,

    /// External Initialization of Trusted Variables or Data Stores
    Cwe454,

    /// Non-exit on Failed Initialization
    Cwe455,

    /// Missing Initialization of a Variable
    Cwe456,

    /// Use of Uninitialized Variable
    Cwe457,

    /// DEPRECATED: Incorrect Initialization
    Cwe458,

    /// Incomplete Cleanup
    Cwe459,

    /// Improper Cleanup on Thrown Exception
    Cwe460,

    /// Duplicate Key in Associative List (Alist)
    Cwe462,

    /// Deletion of Data Structure Sentinel
    Cwe463,

    /// Addition of Data Structure Sentinel
    Cwe464,

    /// Return of Pointer Value Outside of Expected Range
    Cwe466,

    /// Use of sizeof() on a Pointer Type
    Cwe467,

    /// Incorrect Pointer Scaling
    Cwe468,

    /// Use of Pointer Subtraction to Determine Size
    Cwe469,

    /// Use of Externally-Controlled Input to Select Classes or Code ('Unsafe Reflection')
    Cwe470,

    /// Modification of Assumed-Immutable Data (MAID)
    Cwe471,

    /// External Control of Assumed-Immutable Web Parameter
    Cwe472,

    /// PHP External Variable Modification
    Cwe473,

    /// Use of Function with Inconsistent Implementations
    Cwe474,

    /// Undefined Behavior for Input to API
    Cwe475,

    /// NULL Pointer Dereference
    Cwe476,

    /// Use of Obsolete Function
    Cwe477,

    /// Missing Default Case in Multiple Condition Expression
    Cwe478,

    /// Signal Handler Use of a Non-reentrant Function
    Cwe479,

    /// Use of Incorrect Operator
    Cwe480,

    /// Assigning instead of Comparing
    Cwe481,

    /// Comparing instead of Assigning
    Cwe482,

    /// Incorrect Block Delimitation
    Cwe483,

    /// Omitted Break Statement in Switch
    Cwe484,

    /// Comparison of Classes by Name
    Cwe486,

    /// Reliance on Package-level Scope
    Cwe487,

    /// Exposure of Data Element to Wrong Session
    Cwe488,

    /// Active Debug Code
    Cwe489,

    /// Public cloneable() Method Without Final ('Object Hijack')
    Cwe491,

    /// Use of Inner Class Containing Sensitive Data
    Cwe492,

    /// Critical Public Variable Without Final Modifier
    Cwe493,

    /// Download of Code Without Integrity Check
    Cwe494,

    /// Private Data Structure Returned From A Public Method
    Cwe495,

    /// Public Data Assigned to Private Array-Typed Field
    Cwe496,

    /// Exposure of Sensitive System Information to an Unauthorized Control Sphere
    Cwe497,

    /// Cloneable Class Containing Sensitive Information
    Cwe498,

    /// Serializable Class Containing Sensitive Data
    Cwe499,

    /// Public Static Field Not Marked Final
    Cwe500,

    /// Trust Boundary Violation
    Cwe501,

    /// Deserialization of Untrusted Data
    Cwe502,

    /// Embedded Malicious Code
    Cwe506,

    /// Trojan Horse
    Cwe507,

    /// Non-Replicating Malicious Code
    Cwe508,

    /// Replicating Malicious Code (Virus or Worm)
    Cwe509,

    /// Trapdoor
    Cwe510,

    /// Logic/Time Bomb
    Cwe511,

    /// Spyware
    Cwe512,

    /// Covert Channel
    Cwe514,

    /// Covert Storage Channel
    Cwe515,

    /// DEPRECATED: Covert Timing Channel
    Cwe516,

    /// .NET Misconfiguration: Use of Impersonation
    Cwe520,

    /// Weak Password Requirements
    Cwe521,

    /// Insufficiently Protected Credentials
    Cwe522,

    /// Unprotected Transport of Credentials
    Cwe523,

    /// Use of Cache Containing Sensitive Information
    Cwe524,

    /// Use of Web Browser Cache Containing Sensitive Information
    Cwe525,

    /// Cleartext Storage of Sensitive Information in an Environment Variable
    Cwe526,

    /// Exposure of Version-Control Repository to an Unauthorized Control Sphere
    Cwe527,

    /// Exposure of Core Dump File to an Unauthorized Control Sphere
    Cwe528,

    /// Exposure of Access Control List Files to an Unauthorized Control Sphere
    Cwe529,

    /// Exposure of Backup File to an Unauthorized Control Sphere
    Cwe530,

    /// Inclusion of Sensitive Information in Test Code
    Cwe531,

    /// Insertion of Sensitive Information into Log File
    Cwe532,

    /// DEPRECATED: Information Exposure Through Server Log Files
    Cwe533,

    /// DEPRECATED: Information Exposure Through Debug Log Files
    Cwe534,

    /// Exposure of Information Through Shell Error Message
    Cwe535,

    /// Servlet Runtime Error Message Containing Sensitive Information
    Cwe536,

    /// Java Runtime Error Message Containing Sensitive Information
    Cwe537,

    /// Insertion of Sensitive Information into Externally-Accessible File or Directory
    Cwe538,

    /// Use of Persistent Cookies Containing Sensitive Information
    Cwe539,

    /// Inclusion of Sensitive Information in Source Code
    Cwe540,

    /// Inclusion of Sensitive Information in an Include File
    Cwe541,

    /// DEPRECATED: Information Exposure Through Cleanup Log Files
    Cwe542,

    /// Use of Singleton Pattern Without Synchronization in a Multithreaded Context
    Cwe543,

    /// Missing Standardized Error Handling Mechanism
    Cwe544,

    /// DEPRECATED: Use of Dynamic Class Loading
    Cwe545,

    /// Suspicious Comment
    Cwe546,

    /// Use of Hard-coded, Security-relevant Constants
    Cwe547,

    /// Exposure of Information Through Directory Listing
    Cwe548,

    /// Missing Password Field Masking
    Cwe549,

    /// Server-generated Error Message Containing Sensitive Information
    Cwe550,

    /// Incorrect Behavior Order: Authorization Before Parsing and Canonicalization
    Cwe551,

    /// Files or Directories Accessible to External Parties
    Cwe552,

    /// Command Shell in Externally Accessible Directory
    Cwe553,

    /// ASP.NET Misconfiguration: Not Using Input Validation Framework
    Cwe554,

    /// J2EE Misconfiguration: Plaintext Password in Configuration File
    Cwe555,

    /// ASP.NET Misconfiguration: Use of Identity Impersonation
    Cwe556,

    /// Use of getlogin() in Multithreaded Application
    Cwe558,

    /// Use of umask() with chmod-style Argument
    Cwe560,

    /// Dead Code
    Cwe561,

    /// Return of Stack Variable Address
    Cwe562,

    /// Assignment to Variable without Use
    Cwe563,

    /// SQL Injection: Hibernate
    Cwe564,

    /// Reliance on Cookies without Validation and Integrity Checking
    Cwe565,

    /// Authorization Bypass Through User-Controlled SQL Primary Key
    Cwe566,

    /// Unsynchronized Access to Shared Data in a Multithreaded Context
    Cwe567,

    /// finalize() Method Without super.finalize()
    Cwe568,

    /// Expression is Always False
    Cwe570,

    /// Expression is Always True
    Cwe571,

    /// Call to Thread run() instead of start()
    Cwe572,

    /// Improper Following of Specification by Caller
    Cwe573,

    /// EJB Bad Practices: Use of Synchronization Primitives
    Cwe574,

    /// EJB Bad Practices: Use of AWT Swing
    Cwe575,

    /// EJB Bad Practices: Use of Java I/O
    Cwe576,

    /// EJB Bad Practices: Use of Sockets
    Cwe577,

    /// EJB Bad Practices: Use of Class Loader
    Cwe578,

    /// J2EE Bad Practices: Non-serializable Object Stored in Session
    Cwe579,

    /// clone() Method Without super.clone()
    Cwe580,

    /// Object Model Violation: Just One of Equals and Hashcode Defined
    Cwe581,

    /// Array Declared Public, Final, and Static
    Cwe582,

    /// finalize() Method Declared Public
    Cwe583,

    /// Return Inside Finally Block
    Cwe584,

    /// Empty Synchronized Block
    Cwe585,

    /// Explicit Call to Finalize()
    Cwe586,

    /// Assignment of a Fixed Address to a Pointer
    Cwe587,

    /// Attempt to Access Child of a Non-structure Pointer
    Cwe588,

    /// Call to Non-ubiquitous API
    Cwe589,

    /// Free of Memory not on the Heap
    Cwe590,

    /// Sensitive Data Storage in Improperly Locked Memory
    Cwe591,

    /// DEPRECATED: Authentication Bypass Issues
    Cwe592,

    /// Authentication Bypass: OpenSSL CTX Object Modified after SSL Objects are Created
    Cwe593,

    /// J2EE Framework: Saving Unserializable Objects to Disk
    Cwe594,

    /// Comparison of Object References Instead of Object Contents
    Cwe595,

    /// DEPRECATED: Incorrect Semantic Object Comparison
    Cwe596,

    /// Use of Wrong Operator in String Comparison
    Cwe597,

    /// Use of GET Request Method With Sensitive Query Strings
    Cwe598,

    /// Missing Validation of OpenSSL Certificate
    Cwe599,

    /// Uncaught Exception in Servlet
    Cwe600,

    /// URL Redirection to Untrusted Site ('Open Redirect')
    Cwe601,

    /// Client-Side Enforcement of Server-Side Security
    Cwe602,

    /// Use of Client-Side Authentication
    Cwe603,

    /// Multiple Binds to the Same Port
    Cwe605,

    /// Unchecked Input for Loop Condition
    Cwe606,

    /// Public Static Final Field References Mutable Object
    Cwe607,

    /// Struts: Non-private Field in ActionForm Class
    Cwe608,

    /// Double-Checked Locking
    Cwe609,

    /// Externally Controlled Reference to a Resource in Another Sphere
    Cwe610,

    /// Improper Restriction of XML External Entity Reference
    Cwe611,

    /// Improper Authorization of Index Containing Sensitive Information
    Cwe612,

    /// Insufficient Session Expiration
    Cwe613,

    /// Sensitive Cookie in HTTPS Session Without 'Secure' Attribute
    Cwe614,

    /// Inclusion of Sensitive Information in Source Code Comments
    Cwe615,

    /// Incomplete Identification of Uploaded File Variables (PHP)
    Cwe616,

    /// Reachable Assertion
    Cwe617,

    /// Exposed Unsafe ActiveX Method
    Cwe618,

    /// Dangling Database Cursor ('Cursor Injection')
    Cwe619,

    /// Unverified Password Change
    Cwe620,

    /// Variable Extraction Error
    Cwe621,

    /// Improper Validation of Function Hook Arguments
    Cwe622,

    /// Unsafe ActiveX Control Marked Safe For Scripting
    Cwe623,

    /// Executable Regular Expression Error
    Cwe624,

    /// Permissive Regular Expression
    Cwe625,

    /// Null Byte Interaction Error (Poison Null Byte)
    Cwe626,

    /// Dynamic Variable Evaluation
    Cwe627,

    /// Function Call with Incorrectly Specified Arguments
    Cwe628,

    /// Not Failing Securely ('Failing Open')
    Cwe636,

    /// Unnecessary Complexity in Protection Mechanism (Not Using 'Economy of Mechanism')
    Cwe637,

    /// Not Using Complete Mediation
    Cwe638,

    /// Authorization Bypass Through User-Controlled Key
    Cwe639,

    /// Weak Password Recovery Mechanism for Forgotten Password
    Cwe640,

    /// Improper Restriction of Names for Files and Other Resources
    Cwe641,

    /// External Control of Critical State Data
    Cwe642,

    /// Improper Neutralization of Data within XPath Expressions ('XPath Injection')
    Cwe643,

    /// Improper Neutralization of HTTP Headers for Scripting Syntax
    Cwe644,

    /// Overly Restrictive Account Lockout Mechanism
    Cwe645,

    /// Reliance on File Name or Extension of Externally-Supplied File
    Cwe646,

    /// Use of Non-Canonical URL Paths for Authorization Decisions
    Cwe647,

    /// Incorrect Use of Privileged APIs
    Cwe648,

    /// Reliance on Obfuscation or Encryption of Security-Relevant Inputs without Integrity Checking
    Cwe649,

    /// Trusting HTTP Permission Methods on the Server Side
    Cwe650,

    /// Exposure of WSDL File Containing Sensitive Information
    Cwe651,

    /// Improper Neutralization of Data within XQuery Expressions ('XQuery Injection')
    Cwe652,

    /// Improper Isolation or Compartmentalization
    Cwe653,

    /// Reliance on a Single Factor in a Security Decision
    Cwe654,

    /// Insufficient Psychological Acceptability
    Cwe655,

    /// Reliance on Security Through Obscurity
    Cwe656,

    /// Violation of Secure Design Principles
    Cwe657,

    /// Improper Synchronization
    Cwe662,

    /// Use of a Non-reentrant Function in a Concurrent Context
    Cwe663,

    /// Improper Control of a Resource Through its Lifetime
    Cwe664,

    /// Improper Initialization
    Cwe665,

    /// Operation on Resource in Wrong Phase of Lifetime
    Cwe666,

    /// Improper Locking
    Cwe667,

    /// Exposure of Resource to Wrong Sphere
    Cwe668,

    /// Incorrect Resource Transfer Between Spheres
    Cwe669,

    /// Always-Incorrect Control Flow Implementation
    Cwe670,

    /// Lack of Administrator Control over Security
    Cwe671,

    /// Operation on a Resource after Expiration or Release
    Cwe672,

    /// External Influence of Sphere Definition
    Cwe673,

    /// Uncontrolled Recursion
    Cwe674,

    /// Multiple Operations on Resource in Single-Operation Context
    Cwe675,

    /// Use of Potentially Dangerous Function
    Cwe676,

    /// Integer Overflow to Buffer Overflow
    Cwe680,

    /// Incorrect Conversion between Numeric Types
    Cwe681,

    /// Incorrect Calculation
    Cwe682,

    /// Function Call With Incorrect Order of Arguments
    Cwe683,

    /// Incorrect Provision of Specified Functionality
    Cwe684,

    /// Function Call With Incorrect Number of Arguments
    Cwe685,

    /// Function Call With Incorrect Argument Type
    Cwe686,

    /// Function Call With Incorrectly Specified Argument Value
    Cwe687,

    /// Function Call With Incorrect Variable or Reference as Argument
    Cwe688,

    /// Permission Race Condition During Resource Copy
    Cwe689,

    /// Unchecked Return Value to NULL Pointer Dereference
    Cwe690,

    /// Insufficient Control Flow Management
    Cwe691,

    /// Incomplete Denylist to Cross-Site Scripting
    Cwe692,

    /// Protection Mechanism Failure
    Cwe693,

    /// Use of Multiple Resources with Duplicate Identifier
    Cwe694,

    /// Use of Low-Level Functionality
    Cwe695,

    /// Incorrect Behavior Order
    Cwe696,

    /// Incorrect Comparison
    Cwe697,

    /// Execution After Redirect (EAR)
    Cwe698,

    /// Improper Check or Handling of Exceptional Conditions
    Cwe703,

    /// Incorrect Type Conversion or Cast
    Cwe704,

    /// Incorrect Control Flow Scoping
    Cwe705,

    /// Use of Incorrectly-Resolved Name or Reference
    Cwe706,

    /// Improper Neutralization
    Cwe707,

    /// Incorrect Ownership Assignment
    Cwe708,

    /// Improper Adherence to Coding Standards
    Cwe710,

    /// Incorrect Permission Assignment for Critical Resource
    Cwe732,

    /// Compiler Optimization Removal or Modification of Security-critical Code
    Cwe733,

    /// Exposed Dangerous Method or Function
    Cwe749,

    /// Improper Check for Unusual or Exceptional Conditions
    Cwe754,

    /// Improper Handling of Exceptional Conditions
    Cwe755,

    /// Missing Custom Error Page
    Cwe756,

    /// Selection of Less-Secure Algorithm During Negotiation ('Algorithm Downgrade')
    Cwe757,

    /// Reliance on Undefined, Unspecified, or Implementation-Defined Behavior
    Cwe758,

    /// Use of a One-Way Hash without a Salt
    Cwe759,

    /// Use of a One-Way Hash with a Predictable Salt
    Cwe760,

    /// Free of Pointer not at Start of Buffer
    Cwe761,

    /// Mismatched Memory Management Routines
    Cwe762,

    /// Release of Invalid Pointer or Reference
    Cwe763,

    /// Multiple Locks of a Critical Resource
    Cwe764,

    /// Multiple Unlocks of a Critical Resource
    Cwe765,

    /// Critical Data Element Declared Public
    Cwe766,

    /// Access to Critical Private Variable via Public Method
    Cwe767,

    /// Incorrect Short Circuit Evaluation
    Cwe768,

    /// DEPRECATED: Uncontrolled File Descriptor Consumption
    Cwe769,

    /// Allocation of Resources Without Limits or Throttling
    Cwe770,

    /// Missing Reference to Active Allocated Resource
    Cwe771,

    /// Missing Release of Resource after Effective Lifetime
    Cwe772,

    /// Missing Reference to Active File Descriptor or Handle
    Cwe773,

    /// Allocation of File Descriptors or Handles Without Limits or Throttling
    Cwe774,

    /// Missing Release of File Descriptor or Handle after Effective Lifetime
    Cwe775,

    /// Improper Restriction of Recursive Entity References in DTDs ('XML Entity Expansion')
    Cwe776,

    /// Regular Expression without Anchors
    Cwe777,

    /// Insufficient Logging
    Cwe778,

    /// Logging of Excessive Data
    Cwe779,

    /// Use of RSA Algorithm without OAEP
    Cwe780,

    /// Improper Address Validation in IOCTL with METHOD_NEITHER I/O Control Code
    Cwe781,

    /// Exposed IOCTL with Insufficient Access Control
    Cwe782,

    /// Operator Precedence Logic Error
    Cwe783,

    /// Reliance on Cookies without Validation and Integrity Checking in a Security Decision
    Cwe784,

    /// Use of Path Manipulation Function without Maximum-sized Buffer
    Cwe785,

    /// Access of Memory Location Before Start of Buffer
    Cwe786,

    /// Out-of-bounds Write
    Cwe787,

    /// Access of Memory Location After End of Buffer
    Cwe788,

    /// Memory Allocation with Excessive Size Value
    Cwe789,

    /// Improper Filtering of Special Elements
    Cwe790,

    /// Incomplete Filtering of Special Elements
    Cwe791,

    /// Incomplete Filtering of One or More Instances of Special Elements
    Cwe792,

    /// Only Filtering One Instance of a Special Element
    Cwe793,

    /// Incomplete Filtering of Multiple Instances of Special Elements
    Cwe794,

    /// Only Filtering Special Elements at a Specified Location
    Cwe795,

    /// Only Filtering Special Elements Relative to a Marker
    Cwe796,

    /// Only Filtering Special Elements at an Absolute Position
    Cwe797,

    /// Use of Hard-coded Credentials
    Cwe798,

    /// Improper Control of Interaction Frequency
    Cwe799,

    /// Guessable CAPTCHA
    Cwe804,

    /// Buffer Access with Incorrect Length Value
    Cwe805,

    /// Buffer Access Using Size of Source Buffer
    Cwe806,

    /// Reliance on Untrusted Inputs in a Security Decision
    Cwe807,

    /// Missing Synchronization
    Cwe820,

    /// Incorrect Synchronization
    Cwe821,

    /// Untrusted Pointer Dereference
    Cwe822,

    /// Use of Out-of-range Pointer Offset
    Cwe823,

    /// Access of Uninitialized Pointer
    Cwe824,

    /// Expired Pointer Dereference
    Cwe825,

    /// Premature Release of Resource During Expected Lifetime
    Cwe826,

    /// Improper Control of Document Type Definition
    Cwe827,

    /// Signal Handler with Functionality that is not Asynchronous-Safe
    Cwe828,

    /// Inclusion of Functionality from Untrusted Control Sphere
    Cwe829,

    /// Inclusion of Web Functionality from an Untrusted Source
    Cwe830,

    /// Signal Handler Function Associated with Multiple Signals
    Cwe831,

    /// Unlock of a Resource that is not Locked
    Cwe832,

    /// Deadlock
    Cwe833,

    /// Excessive Iteration
    Cwe834,

    /// Loop with Unreachable Exit Condition ('Infinite Loop')
    Cwe835,

    /// Use of Password Hash Instead of Password for Authentication
    Cwe836,

    /// Improper Enforcement of a Single, Unique Action
    Cwe837,

    /// Inappropriate Encoding for Output Context
    Cwe838,

    /// Numeric Range Comparison Without Minimum Check
    Cwe839,

    /// Improper Enforcement of Behavioral Workflow
    Cwe841,

    /// Placement of User into Incorrect Group
    Cwe842,

    /// Access of Resource Using Incompatible Type ('Type Confusion')
    Cwe843,

    /// Missing Authorization
    Cwe862,

    /// Incorrect Authorization
    Cwe863,

    /// Use of Uninitialized Resource
    Cwe908,

    /// Missing Initialization of Resource
    Cwe909,

    /// Use of Expired File Descriptor
    Cwe910,

    /// Improper Update of Reference Count
    Cwe911,

    /// Hidden Functionality
    Cwe912,

    /// Improper Control of Dynamically-Managed Code Resources
    Cwe913,

    /// Improper Control of Dynamically-Identified Variables
    Cwe914,

    /// Improperly Controlled Modification of Dynamically-Determined Object Attributes
    Cwe915,

    /// Use of Password Hash With Insufficient Computational Effort
    Cwe916,

    /// Improper Neutralization of Special Elements used in an Expression Language Statement ('Expression Language Injection')
    Cwe917,

    /// Server-Side Request Forgery (SSRF)
    Cwe918,

    /// Improper Restriction of Power Consumption
    Cwe920,

    /// Storage of Sensitive Data in a Mechanism without Access Control
    Cwe921,

    /// Insecure Storage of Sensitive Information
    Cwe922,

    /// Improper Restriction of Communication Channel to Intended Endpoints
    Cwe923,

    /// Improper Enforcement of Message Integrity During Transmission in a Communication Channel
    Cwe924,

    /// Improper Verification of Intent by Broadcast Receiver
    Cwe925,

    /// Improper Export of Android Application Components
    Cwe926,

    /// Use of Implicit Intent for Sensitive Communication
    Cwe927,

    /// Improper Authorization in Handler for Custom URL Scheme
    Cwe939,

    /// Improper Verification of Source of a Communication Channel
    Cwe940,

    /// Incorrectly Specified Destination in a Communication Channel
    Cwe941,

    /// Permissive Cross-domain Policy with Untrusted Domains
    Cwe942,

    /// Improper Neutralization of Special Elements in Data Query Logic
    Cwe943,

    /// Sensitive Cookie Without 'HttpOnly' Flag
    Cwe1004,

    /// Insufficient Visual Distinction of Homoglyphs Presented to User
    Cwe1007,

    /// Improper Restriction of Rendered UI Layers or Frames
    Cwe1021,

    /// Use of Web Link to Untrusted Target with window.opener Access
    Cwe1022,

    /// Incomplete Comparison with Missing Factors
    Cwe1023,

    /// Comparison of Incompatible Types
    Cwe1024,

    /// Comparison Using Wrong Factors
    Cwe1025,

    /// Processor Optimization Removal or Modification of Security-critical Code
    Cwe1037,

    /// Insecure Automated Optimizations
    Cwe1038,

    /// Automated Recognition Mechanism with Inadequate Detection or Handling of Adversarial Input Perturbations
    Cwe1039,

    /// Use of Redundant Code
    Cwe1041,

    /// Static Member Data Element outside of a Singleton Class Element
    Cwe1042,

    /// Data Element Aggregating an Excessively Large Number of Non-Primitive Elements
    Cwe1043,

    /// Architecture with Number of Horizontal Layers Outside of Expected Range
    Cwe1044,

    /// Parent Class with a Virtual Destructor and a Child Class without a Virtual Destructor
    Cwe1045,

    /// Creation of Immutable Text Using String Concatenation
    Cwe1046,

    /// Modules with Circular Dependencies
    Cwe1047,

    /// Invokable Control Element with Large Number of Outward Calls
    Cwe1048,

    /// Excessive Data Query Operations in a Large Data Table
    Cwe1049,

    /// Excessive Platform Resource Consumption within a Loop
    Cwe1050,

    /// Initialization with Hard-Coded Network Resource Configuration Data
    Cwe1051,

    /// Excessive Use of Hard-Coded Literals in Initialization
    Cwe1052,

    /// Missing Documentation for Design
    Cwe1053,

    /// Invocation of a Control Element at an Unnecessarily Deep Horizontal Layer
    Cwe1054,

    /// Multiple Inheritance from Concrete Classes
    Cwe1055,

    /// Invokable Control Element with Variadic Parameters
    Cwe1056,

    /// Data Access Operations Outside of Expected Data Manager Component
    Cwe1057,

    /// Invokable Control Element in Multi-Thread Context with non-Final Static Storable or Member Element
    Cwe1058,

    /// Insufficient Technical Documentation
    Cwe1059,

    /// Excessive Number of Inefficient Server-Side Data Accesses
    Cwe1060,

    /// Insufficient Encapsulation
    Cwe1061,

    /// Parent Class with References to Child Class
    Cwe1062,

    /// Creation of Class Instance within a Static Code Block
    Cwe1063,

    /// Invokable Control Element with Signature Containing an Excessive Number of Parameters
    Cwe1064,

    /// Runtime Resource Management Control Element in a Component Built to Run on Application Servers
    Cwe1065,

    /// Missing Serialization Control Element
    Cwe1066,

    /// Excessive Execution of Sequential Searches of Data Resource
    Cwe1067,

    /// Inconsistency Between Implementation and Documented Design
    Cwe1068,

    /// Empty Exception Block
    Cwe1069,

    /// Serializable Data Element Containing non-Serializable Item Elements
    Cwe1070,

    /// Empty Code Block
    Cwe1071,

    /// Data Resource Access without Use of Connection Pooling
    Cwe1072,

    /// Non-SQL Invokable Control Element with Excessive Number of Data Resource Accesses
    Cwe1073,

    /// Class with Excessively Deep Inheritance
    Cwe1074,

    /// Unconditional Control Flow Transfer outside of Switch Block
    Cwe1075,

    /// Insufficient Adherence to Expected Conventions
    Cwe1076,

    /// Floating Point Comparison with Incorrect Operator
    Cwe1077,

    /// Inappropriate Source Code Style or Formatting
    Cwe1078,

    /// Parent Class without Virtual Destructor Method
    Cwe1079,

    /// Source Code File with Excessive Number of Lines of Code
    Cwe1080,

    /// Class Instance Self Destruction Control Element
    Cwe1082,

    /// Data Access from Outside Expected Data Manager Component
    Cwe1083,

    /// Invokable Control Element with Excessive File or Data Access Operations
    Cwe1084,

    /// Invokable Control Element with Excessive Volume of Commented-out Code
    Cwe1085,

    /// Class with Excessive Number of Child Classes
    Cwe1086,

    /// Class with Virtual Method without a Virtual Destructor
    Cwe1087,

    /// Synchronous Access of Remote Resource without Timeout
    Cwe1088,

    /// Large Data Table with Excessive Number of Indices
    Cwe1089,

    /// Method Containing Access of a Member Element from Another Class
    Cwe1090,

    /// Use of Object without Invoking Destructor Method
    Cwe1091,

    /// Use of Same Invokable Control Element in Multiple Architectural Layers
    Cwe1092,

    /// Excessively Complex Data Representation
    Cwe1093,

    /// Excessive Index Range Scan for a Data Resource
    Cwe1094,

    /// Loop Condition Value Update within the Loop
    Cwe1095,

    /// Singleton Class Instance Creation without Proper Locking or Synchronization
    Cwe1096,

    /// Persistent Storable Data Element without Associated Comparison Control Element
    Cwe1097,

    /// Data Element containing Pointer Item without Proper Copy Control Element
    Cwe1098,

    /// Inconsistent Naming Conventions for Identifiers
    Cwe1099,

    /// Insufficient Isolation of System-Dependent Functions
    Cwe1100,

    /// Reliance on Runtime Component in Generated Code
    Cwe1101,

    /// Reliance on Machine-Dependent Data Representation
    Cwe1102,

    /// Use of Platform-Dependent Third Party Components
    Cwe1103,

    /// Use of Unmaintained Third Party Components
    Cwe1104,

    /// Insufficient Encapsulation of Machine-Dependent Functionality
    Cwe1105,

    /// Insufficient Use of Symbolic Constants
    Cwe1106,

    /// Insufficient Isolation of Symbolic Constant Definitions
    Cwe1107,

    /// Excessive Reliance on Global Variables
    Cwe1108,

    /// Use of Same Variable for Multiple Purposes
    Cwe1109,

    /// Incomplete Design Documentation
    Cwe1110,

    /// Incomplete I/O Documentation
    Cwe1111,

    /// Incomplete Documentation of Program Execution
    Cwe1112,

    /// Inappropriate Comment Style
    Cwe1113,

    /// Inappropriate Whitespace Style
    Cwe1114,

    /// Source Code Element without Standard Prologue
    Cwe1115,

    /// Inaccurate Comments
    Cwe1116,

    /// Callable with Insufficient Behavioral Summary
    Cwe1117,

    /// Insufficient Documentation of Error Handling Techniques
    Cwe1118,

    /// Excessive Use of Unconditional Branching
    Cwe1119,

    /// Excessive Code Complexity
    Cwe1120,

    /// Excessive McCabe Cyclomatic Complexity
    Cwe1121,

    /// Excessive Halstead Complexity
    Cwe1122,

    /// Excessive Use of Self-Modifying Code
    Cwe1123,

    /// Excessively Deep Nesting
    Cwe1124,

    /// Excessive Attack Surface
    Cwe1125,

    /// Declaration of Variable with Unnecessarily Wide Scope
    Cwe1126,

    /// Compilation with Insufficient Warnings or Errors
    Cwe1127,

    /// Irrelevant Code
    Cwe1164,

    /// Improper Use of Validation Framework
    Cwe1173,

    /// ASP.NET Misconfiguration: Improper Model Validation
    Cwe1174,

    /// Inefficient CPU Computation
    Cwe1176,

    /// Use of Prohibited Code
    Cwe1177,

    /// DEPRECATED: Use of Uninitialized Resource
    Cwe1187,

    /// Initialization of a Resource with an Insecure Default
    Cwe1188,

    /// Improper Isolation of Shared Resources on System-on-a-Chip (SoC)
    Cwe1189,

    /// DMA Device Enabled Too Early in Boot Phase
    Cwe1190,

    /// On-Chip Debug and Test Interface With Improper Access Control
    Cwe1191,

    /// Improper Identifier for IP Block used in System-On-Chip (SOC)
    Cwe1192,

    /// Power-On of Untrusted Execution Core Before Enabling Fabric Access Control
    Cwe1193,

    /// Generation of Weak Initialization Vector (IV)
    Cwe1204,

    /// Failure to Disable Reserved Bits
    Cwe1209,

    /// Insufficient Granularity of Access Control
    Cwe1220,

    /// Incorrect Register Defaults or Module Parameters
    Cwe1221,

    /// Insufficient Granularity of Address Regions Protected by Register Locks
    Cwe1222,

    /// Race Condition for Write-Once Attributes
    Cwe1223,

    /// Improper Restriction of Write-Once Bit Fields
    Cwe1224,

    /// Creation of Emergent Resource
    Cwe1229,

    /// Exposure of Sensitive Information Through Metadata
    Cwe1230,

    /// Improper Prevention of Lock Bit Modification
    Cwe1231,

    /// Improper Lock Behavior After Power State Transition
    Cwe1232,

    /// Security-Sensitive Hardware Controls with Missing Lock Bit Protection
    Cwe1233,

    /// Hardware Internal or Debug Modes Allow Override of Locks
    Cwe1234,

    /// Incorrect Use of Autoboxing and Unboxing for Performance Critical Operations
    Cwe1235,

    /// Improper Neutralization of Formula Elements in a CSV File
    Cwe1236,

    /// Improper Zeroization of Hardware Register
    Cwe1239,

    /// Use of a Cryptographic Primitive with a Risky Implementation
    Cwe1240,

    /// Use of Predictable Algorithm in Random Number Generator
    Cwe1241,

    /// Inclusion of Undocumented Features or Chicken Bits
    Cwe1242,

    /// Sensitive Non-Volatile Information Not Protected During Debug
    Cwe1243,

    /// Internal Asset Exposed to Unsafe Debug Access Level or State
    Cwe1244,

    /// Improper Finite State Machines (FSMs) in Hardware Logic
    Cwe1245,

    /// Improper Write Handling in Limited-write Non-Volatile Memories
    Cwe1246,

    /// Improper Protection Against Voltage and Clock Glitches
    Cwe1247,

    /// Semiconductor Defects in Hardware Logic with Security-Sensitive Implications
    Cwe1248,

    /// Application-Level Admin Tool with Inconsistent View of Underlying Operating System
    Cwe1249,

    /// Improper Preservation of Consistency Between Independent Representations of Shared State
    Cwe1250,

    /// Mirrored Regions with Different Values
    Cwe1251,

    /// CPU Hardware Not Configured to Support Exclusivity of Write and Execute Operations
    Cwe1252,

    /// Incorrect Selection of Fuse Values
    Cwe1253,

    /// Incorrect Comparison Logic Granularity
    Cwe1254,

    /// Comparison Logic is Vulnerable to Power Side-Channel Attacks
    Cwe1255,

    /// Improper Restriction of Software Interfaces to Hardware Features
    Cwe1256,

    /// Improper Access Control Applied to Mirrored or Aliased Memory Regions
    Cwe1257,

    /// Exposure of Sensitive System Information Due to Uncleared Debug Information
    Cwe1258,

    /// Improper Restriction of Security Token Assignment
    Cwe1259,

    /// Improper Handling of Overlap Between Protected Memory Ranges
    Cwe1260,

    /// Improper Handling of Single Event Upsets
    Cwe1261,

    /// Improper Access Control for Register Interface
    Cwe1262,

    /// Improper Physical Access Control
    Cwe1263,

    /// Hardware Logic with Insecure De-Synchronization between Control and Data Channels
    Cwe1264,

    /// Unintended Reentrant Invocation of Non-reentrant Code Via Nested Calls
    Cwe1265,

    /// Improper Scrubbing of Sensitive Data from Decommissioned Device
    Cwe1266,

    /// Policy Uses Obsolete Encoding
    Cwe1267,

    /// Policy Privileges are not Assigned Consistently Between Control and Data Agents
    Cwe1268,

    /// Product Released in Non-Release Configuration
    Cwe1269,

    /// Generation of Incorrect Security Tokens
    Cwe1270,

    /// Uninitialized Value on Reset for Registers Holding Security Settings
    Cwe1271,

    /// Sensitive Information Uncleared Before Debug/Power State Transition
    Cwe1272,

    /// Device Unlock Credential Sharing
    Cwe1273,

    /// Improper Access Control for Volatile Memory Containing Boot Code
    Cwe1274,

    /// Sensitive Cookie with Improper SameSite Attribute
    Cwe1275,

    /// Hardware Child Block Incorrectly Connected to Parent System
    Cwe1276,

    /// Firmware Not Updateable
    Cwe1277,

    /// Missing Protection Against Hardware Reverse Engineering Using Integrated Circuit (IC) Imaging Techniques
    Cwe1278,

    /// Cryptographic Operations are run Before Supporting Units are Ready
    Cwe1279,

    /// Access Control Check Implemented After Asset is Accessed
    Cwe1280,

    /// Sequence of Processor Instructions Leads to Unexpected Behavior
    Cwe1281,

    /// Assumed-Immutable Data is Stored in Writable Memory
    Cwe1282,

    /// Mutable Attestation or Measurement Reporting Data
    Cwe1283,

    /// Improper Validation of Specified Quantity in Input
    Cwe1284,

    /// Improper Validation of Specified Index, Position, or Offset in Input
    Cwe1285,

    /// Improper Validation of Syntactic Correctness of Input
    Cwe1286,

    /// Improper Validation of Specified Type of Input
    Cwe1287,

    /// Improper Validation of Consistency within Input
    Cwe1288,

    /// Improper Validation of Unsafe Equivalence in Input
    Cwe1289,

    /// Incorrect Decoding of Security Identifiers
    Cwe1290,

    /// Public Key Re-Use for Signing both Debug and Production Code
    Cwe1291,

    /// Incorrect Conversion of Security Identifiers
    Cwe1292,

    /// Missing Source Correlation of Multiple Independent Data
    Cwe1293,

    /// Insecure Security Identifier Mechanism
    Cwe1294,

    /// Debug Messages Revealing Unnecessary Information
    Cwe1295,

    /// Incorrect Chaining or Granularity of Debug Components
    Cwe1296,

    /// Unprotected Confidential Information on Device is Accessible by OSAT Vendors
    Cwe1297,

    /// Hardware Logic Contains Race Conditions
    Cwe1298,

    /// Missing Protection Mechanism for Alternate Hardware Interface
    Cwe1299,

    /// Improper Protection of Physical Side Channels
    Cwe1300,

    /// Insufficient or Incomplete Data Removal within Hardware Component
    Cwe1301,

    /// Missing Source Identifier in Entity Transactions on a System-On-Chip (SOC)
    Cwe1302,

    /// Non-Transparent Sharing of Microarchitectural Resources
    Cwe1303,

    /// Improperly Preserved Integrity of Hardware Configuration State During a Power Save/Restore Operation
    Cwe1304,

    /// Missing Ability to Patch ROM Code
    Cwe1310,

    /// Improper Translation of Security Attributes by Fabric Bridge
    Cwe1311,

    /// Missing Protection for Mirrored Regions in On-Chip Fabric Firewall
    Cwe1312,

    /// Hardware Allows Activation of Test or Debug Logic at Runtime
    Cwe1313,

    /// Missing Write Protection for Parametric Data Values
    Cwe1314,

    /// Improper Setting of Bus Controlling Capability in Fabric End-point
    Cwe1315,

    /// Fabric-Address Map Allows Programming of Unwarranted Overlaps of Protected and Unprotected Ranges
    Cwe1316,

    /// Improper Access Control in Fabric Bridge
    Cwe1317,

    /// Missing Support for Security Features in On-chip Fabrics or Buses
    Cwe1318,

    /// Improper Protection against Electromagnetic Fault Injection (EM-FI)
    Cwe1319,

    /// Improper Protection for Outbound Error Messages and Alert Signals
    Cwe1320,

    /// Improperly Controlled Modification of Object Prototype Attributes ('Prototype Pollution')
    Cwe1321,

    /// Use of Blocking Code in Single-threaded, Non-blocking Context
    Cwe1322,

    /// Improper Management of Sensitive Trace Data
    Cwe1323,

    /// DEPRECATED: Sensitive Information Accessible by Physical Probing of JTAG Interface
    Cwe1324,

    /// Improperly Controlled Sequential Memory Allocation
    Cwe1325,

    /// Missing Immutable Root of Trust in Hardware
    Cwe1326,

    /// Binding to an Unrestricted IP Address
    Cwe1327,

    /// Security Version Number Mutable to Older Versions
    Cwe1328,

    /// Reliance on Component That is Not Updateable
    Cwe1329,

    /// Remanent Data Readable after Memory Erase
    Cwe1330,

    /// Improper Isolation of Shared Resources in Network On Chip (NoC)
    Cwe1331,

    /// Improper Handling of Faults that Lead to Instruction Skips
    Cwe1332,

    /// Inefficient Regular Expression Complexity
    Cwe1333,

    /// Unauthorized Error Injection Can Degrade Hardware Redundancy
    Cwe1334,

    /// Incorrect Bitwise Shift of Integer
    Cwe1335,

    /// Improper Neutralization of Special Elements Used in a Template Engine
    Cwe1336,

    /// Improper Protections Against Hardware Overheating
    Cwe1338,

    /// Insufficient Precision or Accuracy of a Real Number
    Cwe1339,

    /// Multiple Releases of Same Resource or Handle
    Cwe1341,

    /// Information Exposure through Microarchitectural State after Transient Execution
    Cwe1342,

    /// Improper Handling of Hardware Behavior in Exceptionally Cold Environments
    Cwe1351,

    /// Reliance on Insufficiently Trustworthy Component
    Cwe1357,

    /// Improper Handling of Physical or Environmental Conditions
    Cwe1384,

    /// Missing Origin Validation in WebSockets
    Cwe1385,

    /// Insecure Operation on Windows Junction / Mount Point
    Cwe1386,

    /// Incorrect Parsing of Numbers with Different Radices
    Cwe1389,

    /// Weak Authentication
    Cwe1390,

    /// Use of Weak Credentials
    Cwe1391,

    /// Use of Default Credentials
    Cwe1392,

    /// Use of Default Password
    Cwe1393,

    /// Use of Default Cryptographic Key
    Cwe1394,

    /// Dependency on Vulnerable Third-Party Component
    Cwe1395,

    /// Incorrect Initialization of Resource
    Cwe1419,

    /// Exposure of Sensitive Information during Transient Execution
    Cwe1420,

    /// Exposure of Sensitive Information in Shared Microarchitectural Structures during Transient Execution
    Cwe1421,

    /// Exposure of Sensitive Information caused by Incorrect Data Forwarding during Transient Execution
    Cwe1422,

    /// Exposure of Sensitive Information caused by Shared Microarchitectural Predictor State that Influences Transient Execution
    Cwe1423,

    /// Improper Validation of Generative AI Output
    Cwe1426,

    /// Improper Neutralization of Input Used for LLM Prompting
    Cwe1427,
}
