name: Run Tests
on: [push, pull_request]

env:
  RUST_BACKTRACE: 1

jobs:
  buildAndTest:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y curl build-essential cmake pkg-config cargo

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: run tests
        run: |
          ./scripts/test.sh
